### ISSUE TITLE
Refactor Project Structure and Remove Unused Components

### ISSUE THREAD

**Issue by juliagolemo** [juliagolemo/learning-journey#39]
#### Description
To improve the organization and maintainability of the codebase, we need to restructure the project by dividing it into clearly defined components and pages. Additionally, some unused elements need to be removed.

#### Tasks

1. **Remove Unused Components**
   - [x] Remove `NavBar` component as it is not in use (we are only using `Sidebar`).
   - [x] Remove the `Pricing` page since it is no longer used.

2. **Create/Organize Components**
   - [x] Ensure the following components are correctly implemented and organized under `src/components`:
     - `Sidebar`

3. **Create/Organize Hooks**
   - [x] Ensure the following custom hooks are implemented and organized under `src/hooks`:
     - `HomeRedirect`
     - `NavigationTracker`

4. **Define and Organize Pages**
   - [x] Structure the following pages in the `src/pages` directory:
     - `Home`
     - `Technologies`
     - `Tutorial`
     - `About`
     - `MarkdownPage`
  
5. **Add and move images to cards to new folder**
   - [x] Add new folder `public/images/cards`

6. **Add new sub-folders for different groups of markdowns**
   - [x] In `public/markdown/` create new sub-folder like `public/markdown/german`,  `public/markdown/golang` and move md to this sub-folders
   - [x] After moving the markdowns, UPDATE paths in JavaScript cards ( like in German.js, Golang.js etc.) or in GenericCardsPage if will be refactored
